# Generated by Django 3.1.7 on 2021-02-25 21:53

import budgetdb.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Financial Institution',
                'verbose_name_plural': 'Financial Institutions',
            },
        ),
        migrations.CreateModel(
            name='BudgetedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budgeted amount')),
                ('percent_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='percent of another event.  say 10% of pay goes to RRSP')),
                ('description', models.CharField(default='Description', max_length=200)),
                ('budget_only', models.BooleanField(default=False, verbose_name='only for budgeting, no actual expense planned')),
                ('isrecurring', models.BooleanField(default=True, verbose_name='Is this a recurring event?')),
                ('repeat_start', models.DateField(verbose_name='date of the first event')),
                ('repeat_stop', models.DateField(blank=True, null=True, verbose_name='date of the last event, optional')),
                ('nb_iteration', models.IntegerField(blank=True, null=True, verbose_name='number of repetitions, null if not applicable')),
                ('repeat_interval_days', models.IntegerField(default=0, verbose_name='period in days, 0 if not applicable')),
                ('repeat_interval_years', models.IntegerField(default=0, verbose_name='period in years, 0 if not applicable')),
                ('repeat_interval_months', models.IntegerField(default=0, verbose_name='period in months, 0 if not applicable')),
                ('repeat_interval_weeks', models.IntegerField(default=0, verbose_name='period in weeks, 0 if not applicable')),
                ('months_mask', budgetdb.models.MyBoolMap(default=4095)),
                ('repeat_months_mask', models.IntegerField(default=4095, verbose_name='binary mask of applicable months. Always Applicable jan=1 feb=2 mar=4 ... dec=2048 ALL=4095')),
                ('repeat_dayofmonth_mask', models.IntegerField(default=2147483647, verbose_name='binary mask of applicable month days. Always Applicable ALL=2147483647')),
                ('repeat_weekofmonth_mask', models.IntegerField(default=31, verbose_name='binary mask of applicable month week. Always Applicable ALL=15')),
                ('repeat_weekday_mask', models.IntegerField(default=127, verbose_name='binary mask of applicable week day. Always Applicable ALL=127')),
                ('BudgetedEvent_percent_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.budgetedevent')),
                ('account_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_account_destination', to='budgetdb.account')),
                ('account_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_account_source', to='budgetdb.account')),
            ],
            options={
                'verbose_name': 'Budgeted Event',
                'verbose_name_plural': 'Budgeted Events',
            },
        ),
        migrations.CreateModel(
            name='Cat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cat2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='CatBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1)),
            ],
            options={
                'verbose_name': 'Category Budget',
                'verbose_name_plural': 'Categories Budgets',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetedEvent_index', models.IntegerField(blank=True, null=True, verbose_name='event index, nth repetition of that budgeted event')),
                ('date_planned', models.DateField(blank=True, null=True, verbose_name='planned date')),
                ('date_actual', models.DateField(verbose_name='date of the transaction')),
                ('amount_actual', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=10, verbose_name='real transaction amount')),
                ('description', models.CharField(max_length=200, verbose_name='transaction description')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='optional comment')),
                ('BudgetedEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.budgetedevent')),
                ('account_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_account_destination', to='budgetdb.account')),
                ('account_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_account_source', to='budgetdb.account')),
                ('cat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat2')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.vendor')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=10, verbose_name='Statement balance')),
                ('statement_date', models.DateField(verbose_name='date of the statement')),
                ('statement_due_date', models.DateField(blank=True, null=True, verbose_name='date where payment is due')),
                ('comment', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_account', to='budgetdb.account')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='cat2',
            name='CatBudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.catbudget'),
        ),
        migrations.AddField(
            model_name='cat2',
            name='cat1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat1'),
        ),
        migrations.AddField(
            model_name='cat1',
            name='CatBudget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.catbudget'),
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='cat2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat2'),
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.vendor'),
        ),
        migrations.CreateModel(
            name='BitmapWeeksPerMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit1', models.BooleanField(default=True, verbose_name='1st')),
                ('bit2', models.BooleanField(default=True, verbose_name='2nd')),
                ('bit3', models.BooleanField(default=True, verbose_name='3rd')),
                ('bit4', models.BooleanField(default=True, verbose_name='4th')),
                ('bit5', models.BooleanField(default=True, verbose_name='5th')),
                ('budgeted_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.budgetedevent')),
            ],
        ),
        migrations.CreateModel(
            name='BitmapWeekdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit1', models.BooleanField(default=True, verbose_name='Mondays')),
                ('bit2', models.BooleanField(default=True, verbose_name='Tuesdays')),
                ('bit3', models.BooleanField(default=True, verbose_name='Wednesdays')),
                ('bit4', models.BooleanField(default=True, verbose_name='Thursdays')),
                ('bit5', models.BooleanField(default=True, verbose_name='Fridays')),
                ('bit6', models.BooleanField(default=True, verbose_name='Saturdays')),
                ('bit7', models.BooleanField(default=True, verbose_name='Sundays')),
                ('budgeted_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.budgetedevent')),
            ],
        ),
        migrations.CreateModel(
            name='BitmapMonths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit1', models.BooleanField(default=True, verbose_name='Jan')),
                ('bit2', models.BooleanField(default=True, verbose_name='Feb')),
                ('bit3', models.BooleanField(default=True, verbose_name='Mar')),
                ('bit4', models.BooleanField(default=True, verbose_name='Apr')),
                ('bit5', models.BooleanField(default=True, verbose_name='May')),
                ('bit6', models.BooleanField(default=True, verbose_name='Jun')),
                ('bit7', models.BooleanField(default=True, verbose_name='Jul')),
                ('bit8', models.BooleanField(default=True, verbose_name='Aug')),
                ('bit9', models.BooleanField(default=True, verbose_name='Sep')),
                ('bit10', models.BooleanField(default=True, verbose_name='Oct')),
                ('bit11', models.BooleanField(default=True, verbose_name='Nov')),
                ('bit12', models.BooleanField(default=True, verbose_name='Dec')),
                ('budgeted_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.budgetedevent')),
            ],
        ),
        migrations.CreateModel(
            name='BitmapDayPerMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit1', models.BooleanField(default=True, verbose_name='1')),
                ('bit2', models.BooleanField(default=True, verbose_name='2')),
                ('bit3', models.BooleanField(default=True, verbose_name='3')),
                ('bit4', models.BooleanField(default=True, verbose_name='4')),
                ('bit5', models.BooleanField(default=True, verbose_name='5')),
                ('bit6', models.BooleanField(default=True, verbose_name='6')),
                ('bit7', models.BooleanField(default=True, verbose_name='7')),
                ('bit8', models.BooleanField(default=True, verbose_name='8')),
                ('bit9', models.BooleanField(default=True, verbose_name='9')),
                ('bit10', models.BooleanField(default=True, verbose_name='10')),
                ('bit11', models.BooleanField(default=True, verbose_name='11')),
                ('bit12', models.BooleanField(default=True, verbose_name='12')),
                ('bit13', models.BooleanField(default=True, verbose_name='13')),
                ('bit14', models.BooleanField(default=True, verbose_name='14')),
                ('bit15', models.BooleanField(default=True, verbose_name='15')),
                ('bit16', models.BooleanField(default=True, verbose_name='16')),
                ('bit17', models.BooleanField(default=True, verbose_name='17')),
                ('bit18', models.BooleanField(default=True, verbose_name='18')),
                ('bit19', models.BooleanField(default=True, verbose_name='19')),
                ('bit20', models.BooleanField(default=True, verbose_name='20')),
                ('bit21', models.BooleanField(default=True, verbose_name='21')),
                ('bit22', models.BooleanField(default=True, verbose_name='22')),
                ('bit23', models.BooleanField(default=True, verbose_name='23')),
                ('bit24', models.BooleanField(default=True, verbose_name='24')),
                ('bit25', models.BooleanField(default=True, verbose_name='25')),
                ('bit26', models.BooleanField(default=True, verbose_name='26')),
                ('bit27', models.BooleanField(default=True, verbose_name='27')),
                ('bit28', models.BooleanField(default=True, verbose_name='28')),
                ('bit29', models.BooleanField(default=True, verbose_name='29')),
                ('bit30', models.BooleanField(default=True, verbose_name='30')),
                ('bit31', models.BooleanField(default=True, verbose_name='31')),
                ('budgeted_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.budgetedevent')),
            ],
        ),
        migrations.CreateModel(
            name='AccountAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(verbose_name='date of the audit')),
                ('audit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=10, verbose_name='audit amount')),
                ('comment', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_account', to='budgetdb.account')),
            ],
            options={
                'verbose_name': 'Account audit point',
                'verbose_name_plural': 'Account audit points',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='AccountHost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.accounthost'),
        ),
    ]
