# Generated by Django 3.1.7 on 2021-03-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0005_mycalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'db_table': 'calendar_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='cat1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat1', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='cat2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat2', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='repeat_weekofmonth_mask',
            field=models.IntegerField(default=63, verbose_name='binary mask of applicable month week. Always Applicable ALL=15'),
        ),
    ]
