# Generated by Django 3.1.7 on 2021-03-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0010_transaction_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarView',
        ),
    ]
