# Generated by Django 3.1.7 on 2021-03-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0011_delete_calendarview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitmapmonths',
            name='budgeted_event',
        ),
        migrations.RemoveField(
            model_name='bitmapweekdays',
            name='budgeted_event',
        ),
        migrations.RemoveField(
            model_name='bitmapweekspermonth',
            name='budgeted_event',
        ),
        migrations.RemoveField(
            model_name='budgetedevent',
            name='months_mask',
        ),
        migrations.DeleteModel(
            name='BitmapDayPerMonth',
        ),
        migrations.DeleteModel(
            name='BitmapMonths',
        ),
        migrations.DeleteModel(
            name='BitmapWeekdays',
        ),
        migrations.DeleteModel(
            name='BitmapWeeksPerMonth',
        ),
    ]
