# Generated by Django 3.1.7 on 2021-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0016_auto_20210325_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='balance for the day')),
            ],
            options={
                'db_table': 'budgetdb_cattotals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category Type',
                'verbose_name_plural': 'Categories Type',
            },
        ),
        migrations.RenameField(
            model_name='budgetedevent',
            old_name='BudgetedEvent_percent_ref',
            new_name='budgetedevent_percent_ref',
        ),
    ]
