# Generated by Django 3.1.7 on 2021-03-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0017_auto_20210329_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat1',
            name='cattype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cattype'),
        ),
        migrations.AddField(
            model_name='cat2',
            name='cattype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cattype'),
        ),
    ]
