# Generated by Django 3.1.7 on 2021-03-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0018_auto_20210329_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1',
            name='cattype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cattype'),
        ),
        migrations.AlterField(
            model_name='cat2',
            name='cattype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cattype'),
        ),
    ]
