# Generated by Django 3.1.7 on 2021-04-07 14:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0020_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget_only',
            field=models.BooleanField(default=False, verbose_name='counts as 0 after today, only exists to simulate future expenses'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.BooleanField(default=False, verbose_name='Checked with receipt'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='transaction amount'),
        ),
    ]
