# Generated by Django 3.1.7 on 2021-05-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0027_auto_20210510_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_interval_start', models.DateTimeField(blank=True, null=True, verbose_name='begining of the generated events interval')),
                ('generated_interval_stop', models.DateTimeField(blank=True, null=True, verbose_name='end of the generated events interval')),
                ('repeat_start', models.DateField(verbose_name='date of the first event')),
                ('repeat_stop', models.DateField(blank=True, null=True, verbose_name='date of the last event, optional')),
                ('nb_iteration', models.IntegerField(blank=True, null=True, verbose_name='number of repetitions, null if not applicable')),
                ('repeat_interval_days', models.IntegerField(default=0, verbose_name='period in days, 0 if not applicable')),
                ('repeat_interval_years', models.IntegerField(default=0, verbose_name='period in years, 0 if not applicable')),
                ('repeat_interval_months', models.IntegerField(default=0, verbose_name='period in months, 0 if not applicable')),
                ('repeat_interval_weeks', models.IntegerField(default=0, verbose_name='period in weeks, 0 if not applicable')),
                ('repeat_months_mask', models.IntegerField(default=4095, verbose_name='binary mask of applicable months. Always Applicable jan=1 feb=2 mar=4 ... dec=2048 ALL=4095')),
                ('repeat_dayofmonth_mask', models.IntegerField(default=2147483647, verbose_name='binary mask of applicable month days. Always Applicable ALL=2147483647')),
                ('repeat_weekofmonth_mask', models.IntegerField(default=63, verbose_name='binary mask of applicable month week. Always Applicable ALL=15')),
                ('repeat_weekday_mask', models.IntegerField(default=127, verbose_name='binary mask of applicable week day. Always Applicable ALL=127')),
            ],
            options={
                'verbose_name': 'Recurring',
                'verbose_name_plural': 'Recurring',
            },
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='generated_interval_start',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='generated_interval_stop',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='nb_iteration',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_dayofmonth_mask',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_interval_days',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_interval_months',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_interval_weeks',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_interval_years',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_months_mask',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_start',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_stop',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_weekday_mask',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='repeat_weekofmonth_mask',
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='isrecurring',
            field=models.BooleanField(default=True, verbose_name='Is this a recurring event?'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='recurring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.recurring'),
        ),
    ]
