# Generated by Django 3.1.7 on 2021-08-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0028_auto_20210520_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedevent',
            name='ismanual',
            field=models.BooleanField(default=False, verbose_name='Is this an event that require manual intervention?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ismanual',
            field=models.BooleanField(default=False, verbose_name='Is this an event that require manual intervention?'),
        ),
    ]
