# Generated by Django 4.0.2 on 2022-02-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0033_transaction_fuel_l_transaction_fuel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='max_interval_slider',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='min_interval_slider',
            field=models.DateField(blank=True, null=True),
        ),
    ]
