# Generated by Django 4.0.2 on 2022-03-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
