# Generated by Django 5.0.1 on 2024-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Balance'),
        ),
    ]
