# Generated by Django 6.0.3 on 2026-03-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystubmapping',
            name='entry_type',
            field=models.CharField(choices=[('1.0', 'Income (+)'), ('-1.0', 'Deduction (-)')], default='1.0', help_text='Determines if the value adds to or subtracts from the total.', max_length=10),
        ),
        migrations.AlterField(
            model_name='paystubmapping',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
