# Generated by Django 5.0.1 on 2024-02-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0002_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
    ]
