# Generated by Django 6.0.3 on 2026-03-17 10:55

from django.db import migrations

def copy_multiplier_to_entry_type(apps, schema_editor):
    PaystubMapping = apps.get_model('budgetdb', 'PaystubMapping')
    for mapping in PaystubMapping.objects.all():
        # Convert the decimal/float to the exact string expected by choices
        if mapping.multiplier < 0:
            mapping.entry_type = '-1.0'
        else:
            mapping.entry_type = '1.0'
        mapping.save()

class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0002_paystubmapping_entry_type_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_multiplier_to_entry_type),
    ]