# Generated by Django 3.1.7 on 2021-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0002_catbudget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='00000', max_length=200),
            preserve_default=False,
        ),
    ]
