# Generated by Django 3.1.7 on 2021-03-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0003_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedevent',
            name='cat1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='cat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.cat1'),
        ),
        migrations.AlterField(
            model_name='catbudget',
            name='amount_frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='D', max_length=1),
        ),
    ]
