# Generated by Django 6.0.3 on 2026-03-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0003_auto_20260317_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystubmapping',
            name='multiplier',
        ),
    ]
