# Generated by Django 4.0.2 on 2022-03-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0004_account_deleted_at_account_deleted_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountAudit',
        ),
    ]
