# Generated by Django 3.1.7 on 2021-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0004_auto_20210303_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_date', models.DateField(verbose_name='date')),
                ('year', models.IntegerField(verbose_name='year')),
                ('month', models.IntegerField(verbose_name='month')),
                ('day', models.IntegerField(verbose_name='year')),
                ('quarter', models.IntegerField(verbose_name='quarter')),
                ('week', models.IntegerField(verbose_name='week')),
                ('day_name', models.CharField(max_length=9, verbose_name='Day name EN')),
                ('month_name', models.CharField(max_length=9, verbose_name='Month Name EN')),
                ('holiday_flag', models.BooleanField(default=False, verbose_name='Holiday Flag')),
                ('weekend_flag', models.BooleanField(default=False, verbose_name='Weekend Flag')),
                ('event', models.CharField(max_length=50, verbose_name='Event name')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
            },
        ),
    ]
