# Generated by Django 6.0.3 on 2026-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0005_populate_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='day',
            field=models.IntegerField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='mycalendar',
            name='db_date',
            field=models.DateField(unique=True, verbose_name='date'),
        ),
    ]
