# Generated by Django 5.0.2 on 2024-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0005_alter_cattype_options_accountbalancedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalancedb',
            name='balance_is_dirty',
            field=models.BooleanField(default=True, verbose_name='If there is a new transaction for this day, the balance is not reliable'),
        ),
    ]
