# Generated by Django 5.0.2 on 2024-02-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0006_accountbalancedb_balance_is_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalancedb',
            name='balance_is_dirty',
            field=models.BooleanField(default=False, verbose_name='If there is a new transaction for this day, the balance is not reliable'),
        ),
    ]
