# Generated by Django 6.0.3 on 2026-03-20 11:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0006_alter_mycalendar_day_alter_mycalendar_db_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='calc_mode',
            field=models.CharField(choices=[('SUM', 'Strict Sum of Children'), ('OVR', 'Parent Audit Overrides (Hybrid)')], default='SUM', max_length=3),
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budgetdb.account'),
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='audit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='audited amount'),
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='balance for the day'),
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='db_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='relative change'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalancedb',
            unique_together={('account', 'db_date')},
        ),
        migrations.AddIndex(
            model_name='accountbalancedb',
            index=models.Index(fields=['account', 'db_date'], name='budgetdb_ac_account_48dff1_idx'),
        ),
    ]
