# Generated by Django 4.0.2 on 2022-03-16 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('budgetdb', '0007_alter_account_deleted_by_alter_account_groups_mod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='groups_mod',
            field=models.ManyToManyField(related_name='g_can_mod_%(app_label)s_%(class)s', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='groups_view',
            field=models.ManyToManyField(related_name='g_can_view_%(app_label)s_%(class)s', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
