# Generated by Django 5.0.2 on 2024-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0007_alter_accountbalancedb_balance_is_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalancedb',
            name='is_audit',
            field=models.BooleanField(default=False, verbose_name='override of the account balance'),
        ),
    ]
