# Generated by Django 6.0.3 on 2026-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0007_account_calc_mode_alter_accountbalancedb_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fit_id_transfer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
