# Generated by Django 5.0.2 on 2024-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0008_accountbalancedb_is_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='theme',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Dark', max_length=15, verbose_name='Color Mode'),
        ),
    ]
