# Generated by Django 6.0.3 on 2026-03-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0008_transaction_fit_id_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ofx_flip_sign_set',
            field=models.BooleanField(default=False),
        ),
    ]
