# Generated by Django 3.1.7 on 2021-03-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0008_auto_20210314_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='confirmed in a statement.  Prevents deletion in case of budgetedEvent change'),
        ),
    ]
