# Generated by Django 6.0.3 on 2026-03-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0009_account_ofx_flip_sign_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatSums',
        ),
        migrations.AlterField(
            model_name='account',
            name='ofx_flip_sign_set',
            field=models.BooleanField(default=False, help_text="don't ask user for flip sign"),
        ),
    ]
