# Generated by Django 3.1.7 on 2021-03-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0009_transaction_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='audit',
            field=models.BooleanField(default=False, verbose_name='Special transaction that overrides an account balance.  Used to set the initial value.  Use account_source as account_id'),
        ),
    ]
