# Generated by Django 5.0.2 on 2024-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0009_preference_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('message_type', models.CharField(choices=[('tutorial', 'Tutorial')], default='Tutorial', max_length=15, verbose_name='Type')),
            ],
        ),
        migrations.AlterField(
            model_name='preference',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='Dark', max_length=15, verbose_name='Color Mode'),
        ),
    ]
