# Generated by Django 6.0.3 on 2026-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0010_delete_catsums_alter_account_ofx_flip_sign_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AlterField(
            model_name='preference',
            name='statement_buffer_after',
            field=models.IntegerField(default=0, verbose_name='days after statement date in transactionlist view'),
        ),
    ]
