# Generated by Django 5.0.2 on 2024-02-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0010_messages_alter_preference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='testsrtdfcurrencies',
            field=models.CharField(default='Dadfgrk', max_length=15, verbose_name='Color Mdfgdfgode'),
        ),
    ]
