# Generated by Django 4.0.2 on 2022-03-20 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0010_user_friends_user_invited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.RenameField(
            model_name='accountcategory',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.RenameField(
            model_name='accounthost',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.RenameField(
            model_name='cat1',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.RenameField(
            model_name='cat2',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.RenameField(
            model_name='cattype',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='groups_mod',
            new_name='groups_admin',
        ),
        migrations.AddField(
            model_name='account',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounthost',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounthost',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat1',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat1',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat2',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat2',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cattype',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cattype',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='users_admin',
            field=models.ManyToManyField(related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='users_view',
            field=models.ManyToManyField(related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
