# Generated by Django 6.0.3 on 2026-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0011_remove_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystub_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
