# Generated by Django 5.0.2 on 2024-02-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0012_remove_preference_testsrtdfcurrencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='start_interval',
            new_name='slider_start',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='end_interval',
            new_name='slider_stop',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='min_interval_slider',
            new_name='timeline_start',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='max_interval_slider',
            new_name='timeline_stop',
        ),
    ]
