# Generated by Django 6.0.3 on 2026-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0012_transaction_paystub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystubmapping',
            name='is_pass_through',
            field=models.BooleanField(default=False),
        ),
    ]
