# Generated by Django 3.1.7 on 2021-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0012_auto_20210315_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_date', models.DateField(blank=True)),
                ('audit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='audited amount')),
                ('delta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='relative change for the day')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='balance for the day')),
            ],
            options={
                'db_table': 'budgetdb_accounttotal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.ManyToManyField(related_name='account_categories', to='budgetdb.Account')),
            ],
            options={
                'verbose_name': 'Account Category',
                'verbose_name_plural': 'Account Categories',
            },
        ),
    ]
