# Generated by Django 5.0.2 on 2024-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0013_rename_start_interval_preference_slider_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default='2018-01-01', verbose_name='date opened'),
        ),
    ]
