# Generated by Django 6.0.3 on 2026-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0013_paystubmapping_is_pass_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystubmapping',
            name='token_count',
            field=models.IntegerField(default=0, help_text='number of token for this line'),
        ),
    ]
