# Generated by Django 4.0.2 on 2022-03-22 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0013_remove_account_groups_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedevent',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='users_admin',
            field=models.ManyToManyField(blank=True, related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='users_view',
            field=models.ManyToManyField(blank=True, related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='users_admin',
            field=models.ManyToManyField(blank=True, related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='users_view',
            field=models.ManyToManyField(blank=True, related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
