# Generated by Django 5.0.2 on 2024-03-15 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0014_alter_account_date_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalancedb',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='balance for the day'),
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='relative change for the day'),
        ),
    ]
