# Generated by Django 6.0.5 on 2026-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0014_paystubmapping_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='account_sort_default_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preference',
            name='account_sort_default_field',
            field=models.CharField(default='date_actual', max_length=100),
            preserve_default=False,
        ),
    ]
