# Generated by Django 3.1.7 on 2021-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0014_auto_20210320_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedevent',
            name='generated_interval_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='begining of the generated events interval'),
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='generated_interval_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end of the generated events interval'),
        ),
    ]
