# Generated by Django 3.1.7 on 2021-03-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0015_auto_20210322_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='BudgetedEvent',
            new_name='budgetedevent',
        ),
    ]
