# Generated by Django 6.0.5 on 2026-06-06 08:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0015_preference_account_sort_default_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedevent',
            name='cat1',
            field=models.ForeignKey(blank=True, help_text='Transaction Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='budgetdb.cat1', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='cat2',
            field=models.ForeignKey(blank=True, help_text='Transaction Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='description',
            field=models.CharField(help_text='Transaction Description', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='account_sort_default_field',
            field=models.CharField(default='date_actual', max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='cat1',
            field=models.ForeignKey(blank=True, help_text='Transaction Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='budgetdb.cat1', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='template',
            name='cat2',
            field=models.ForeignKey(blank=True, help_text='Transaction Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(help_text='Transaction Description', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction Amount', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='audit',
            field=models.BooleanField(default=False, help_text='Transaction Audit state', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat1',
            field=models.ForeignKey(blank=True, help_text='Transaction Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='budgetdb.cat1', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat2',
            field=models.ForeignKey(blank=True, help_text='Transaction Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_actual',
            field=models.DateField(help_text='Transaction Date', verbose_name='date of the transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(help_text='Transaction Description', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.BooleanField(default=False, help_text='Transaction Receipt state', verbose_name='Checked with receipt'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(blank=True, help_text='Transaction Statement Date', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgetdb.statement'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(default=False, help_text='Transaction Verified state', verbose_name='Verified in a statement'),
        ),
    ]
