# Generated by Django 4.0.2 on 2022-03-25 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0015_remove_account_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('view_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetedevent',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cat1',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cat2',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='catbudget',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cattype',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='joinedtransactions',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='deleted',
        ),
        migrations.AddField(
            model_name='statement',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='users_admin',
            field=models.ManyToManyField(blank=True, related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='users_view',
            field=models.ManyToManyField(blank=True, related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
