# Generated by Django 5.0.2 on 2024-03-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0015_alter_accountbalancedb_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedevent',
            name='generated_interval_start',
            field=models.DateField(blank=True, null=True, verbose_name='begining of the generated events interval'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='generated_interval_stop',
            field=models.DateField(blank=True, null=True, verbose_name='end of the generated events interval'),
        ),
    ]
