# Generated by Django 4.0.2 on 2022-03-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0016_alter_transaction_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
    ]
