# Generated by Django 5.2.3 on 2025-07-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0016_alter_budgetedevent_generated_interval_start_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalances',
        ),
        migrations.RenameField(
            model_name='cat2',
            old_name='fuel',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Fuel_L',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Fuel_price',
        ),
        migrations.AlterField(
            model_name='accountbalancedb',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.account'),
        ),
    ]
