# Generated by Django 5.2.3 on 2025-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0017_delete_accountbalances_rename_fuel_cat2_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat2',
            name='unit_price',
            field=models.BooleanField(default=False, verbose_name='Do we keep unit quantity and cost per for this subcategory'),
        ),
    ]
