# Generated by Django 5.2.3 on 2025-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0018_alter_cat2_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unit_price',
            field=models.BooleanField(default=False, verbose_name='Do we keep unit quantity and cost per for this account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Unit_QTY',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Price per'),
        ),
    ]
