# Generated by Django 4.0.2 on 2023-02-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0019_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_closed',
            field=models.DateField(blank=True, null=True, verbose_name='date closed'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(blank=True, null=True, verbose_name='date opened'),
        ),
    ]
