# Generated by Django 6.0.1 on 2026-02-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0019_account_unit_price_alter_transaction_unit_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fit_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ODX_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
