# Generated by Django 6.0.1 on 2026-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0020_transaction_fit_id_vendor_odx_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fit_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
