# Generated by Django 3.1.7 on 2021-04-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0021_auto_20210407_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='AccountHost',
            new_name='account_host',
        ),
        migrations.AddField(
            model_name='account',
            name='account_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
