# Generated by Django 6.0.1 on 2026-02-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0021_alter_transaction_fit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='ODX_name',
            new_name='OFX_name',
        ),
    ]
