# Generated by Django 3.1.7 on 2021-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0022_auto_20210409_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_planned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='planned amount'),
        ),
    ]
