# Generated by Django 6.0.1 on 2026-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0022_rename_odx_name_vendor_ofx_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ofx_acct_id',
            field=models.CharField(blank=True, help_text="Bank's ACCTID from OFX", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='OFX_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank import key'),
        ),
    ]
