# Generated by Django 6.0.1 on 2026-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0023_account_ofx_acct_id_alter_vendor_ofx_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ofx_fid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ofx_flip_sign',
            field=models.BooleanField(default=False, help_text='Check if outflows are positive in OFX'),
        ),
        migrations.AddField(
            model_name='account',
            name='ofx_org',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
