# Generated by Django 3.1.7 on 2021-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0023_transaction_amount_planned'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPresentation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=200)),
                ('childrens', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'budgetdb_account_presentation',
                'managed': False,
            },
        ),
    ]
