# Generated by Django 4.0.2 on 2023-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0024_transaction_amount_actual_foreign_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_short',
            field=models.CharField(default='b', max_length=10),
            preserve_default=False,
        ),
    ]
