# Generated by Django 6.0.1 on 2026-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0024_account_ofx_fid_account_ofx_flip_sign_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('account_source', 'fit_id'), name='unique_fit_id_per_account'),
        ),
    ]
