# Generated by Django 4.0.2 on 2023-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0025_currency_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='b', max_length=5),
            preserve_default=False,
        ),
    ]
