# Generated by Django 3.1.7 on 2021-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0026_auto_20210424_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedtransactions',
            name='generated_interval_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='begining of the generated events interval'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='generated_interval_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end of the generated events interval'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='nb_iteration',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of repetitions, null if not applicable'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_dayofmonth_mask',
            field=models.IntegerField(default=2147483647, verbose_name='binary mask of applicable month days. Always Applicable ALL=2147483647'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_interval_days',
            field=models.IntegerField(default=0, verbose_name='period in days, 0 if not applicable'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_interval_months',
            field=models.IntegerField(default=0, verbose_name='period in months, 0 if not applicable'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_interval_weeks',
            field=models.IntegerField(default=0, verbose_name='period in weeks, 0 if not applicable'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_interval_years',
            field=models.IntegerField(default=0, verbose_name='period in years, 0 if not applicable'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_months_mask',
            field=models.IntegerField(default=4095, verbose_name='binary mask of applicable months. Always Applicable jan=1 feb=2 mar=4 ... dec=2048 ALL=4095'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_start',
            field=models.DateField(default='2021-05-10', verbose_name='date of the first event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_stop',
            field=models.DateField(blank=True, null=True, verbose_name='date of the last event, optional'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_weekday_mask',
            field=models.IntegerField(default=127, verbose_name='binary mask of applicable week day. Always Applicable ALL=127'),
        ),
        migrations.AddField(
            model_name='joinedtransactions',
            name='repeat_weekofmonth_mask',
            field=models.IntegerField(default=63, verbose_name='binary mask of applicable month week. Always Applicable ALL=15'),
        ),
    ]
