# Generated by Django 6.0.1 on 2026-02-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0026_alter_account_deleted_at_alter_account_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_fit_id_per_account',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('account_source', 'fit_id'), name='unique_fit_id_per_account'),
        ),
    ]
