# Generated by Django 4.0.2 on 2023-02-19 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0027_account_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Fuel_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Fuel cost per'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_owner_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('users_admin', models.ManyToManyField(blank=True, related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('users_view', models.ManyToManyField(blank=True, related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
                'ordering': ['email'],
            },
        ),
    ]
