# Generated by Django 6.0.2 on 2026-02-19 15:29

import budgetdb.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0027_remove_transaction_unique_fit_id_per_account_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', budgetdb.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment due date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgetdb.statement'),
        ),
    ]
