# Generated by Django 6.0.2 on 2026-02-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0028_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='vreified_lock',
            field=models.BooleanField(default=False, verbose_name='Total is good, all transactions verified, lock status'),
        ),
    ]
