# Generated by Django 4.0.2 on 2023-03-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0028_alter_currency_options_alter_transaction_fuel_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['email'], 'verbose_name': 'Invitation', 'verbose_name_plural': 'Invitations'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
    ]
