# Generated by Django 6.0.2 on 2026-02-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0029_statement_vreified_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='vreified_lock',
            new_name='verified_lock',
        ),
    ]
