# Generated by Django 4.0.2 on 2023-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0029_alter_friend_options_alter_vendor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tdate_planned',
            field=models.DateField(blank=True, null=True, verbose_name='planned date'),
        ),
    ]
