# Generated by Django 4.0.2 on 2023-03-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0030_transaction_tdate_planned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tdate_planned',
        ),
    ]
