# Generated by Django 6.0.2 on 2026-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0030_rename_vreified_lock_statement_verified_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='statement_buffer_after',
            field=models.IntegerField(default=0, verbose_name='days before statement date in transactionlist view'),
        ),
        migrations.AddField(
            model_name='preference',
            name='statement_buffer_before',
            field=models.IntegerField(default=36, verbose_name='days before statement date in transactionlist view'),
        ),
    ]
