# Generated by Django 4.0.2 on 2023-03-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0031_remove_transaction_tdate_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedevent',
            name='account_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.account'),
        ),
    ]
