# Generated by Django 4.0.2 on 2022-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0031_statement_minimum_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment'),
        ),
    ]
