# Generated by Django 4.0.2 on 2022-02-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0032_account_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Fuel_L',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Fuel quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Fuel_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Fuel cost'),
        ),
    ]
