# Generated by Django 4.0.2 on 2023-03-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0033_alter_budgetedevent_account_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedevent',
            name='account_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account_destination', to='budgetdb.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account_destination', to='budgetdb.account'),
        ),
    ]
