# Generated by Django 4.0.2 on 2022-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0034_preference_max_interval_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='RRSP',
            field=models.BooleanField(default=False, verbose_name='Account is a RRSP for canadian fiscal considerations'),
        ),
        migrations.AddField(
            model_name='account',
            name='TFSA',
            field=models.BooleanField(default=False, verbose_name='Account is a TFSA for canadian fiscal considerations'),
        ),
    ]
