# Generated by Django 4.0.2 on 2023-03-08 23:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0034_alter_budgetedevent_account_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedevent',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='original amount'),
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='budgetdb.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='original amount'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='amount_planned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='planned amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='budgetdb.cat1', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Subcategory'),
        ),
    ]
