# Generated by Django 4.0.2 on 2022-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0035_account_rrsp_account_tfsa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'ordering': ['name'], 'verbose_name': 'Account Category', 'verbose_name_plural': 'Account Categories'},
        ),
        migrations.AlterModelOptions(
            name='accounthost',
            options={'ordering': ['name'], 'verbose_name': 'Financial Institution', 'verbose_name_plural': 'Financial Institutions'},
        ),
        migrations.AlterModelOptions(
            name='accountpresentation',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cat1',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cat2',
            options={'ordering': ['name'], 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Account audit point', 'verbose_name_plural': 'Account audit points'},
        ),
        migrations.AddField(
            model_name='budgetedevent',
            name='joined_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='position in a joined transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='audit',
            field=models.BooleanField(default=False, verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified in a statement'),
        ),
    ]
