# Generated by Django 4.0.2 on 2023-03-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0035_budgetedevent_amount_planned_foreign_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedevent',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
