# Generated by Django 4.0.2 on 2022-02-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0036_alter_account_options_alter_accountcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='joined_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='position in a joined transaction'),
        ),
    ]
