# Generated by Django 4.0.2 on 2023-03-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0036_alter_budgetedevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetedevent',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='optional comment'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='budget_only',
            field=models.BooleanField(default=False, verbose_name='counts as 0 after today, only exists to simulate future expenses'),
        ),
    ]
