# Generated by Django 4.0.2 on 2023-05-13 02:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0039_remove_joinedtransactions_recurring_delete_recurring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat2',
            options={'ordering': ['name'], 'verbose_name': 'Sub-Category', 'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['-statement_date'], 'verbose_name': 'Statement', 'verbose_name_plural': 'Statements'},
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='original amount'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='budget_only',
            field=models.BooleanField(default=False, verbose_name='Budget only, counts as 0 after today'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='cat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='ismanual',
            field=models.BooleanField(default=False, verbose_name='Manual Intervention?'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='nb_iteration',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of repetitions, null if N/A'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='repeat_interval_days',
            field=models.IntegerField(default=0, verbose_name='period in days, 0 if N/A'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='repeat_interval_months',
            field=models.IntegerField(default=0, verbose_name='period in months, 0 if N/A'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='repeat_interval_weeks',
            field=models.IntegerField(default=0, verbose_name='period in weeks, 0 if N/A'),
        ),
        migrations.AlterField(
            model_name='budgetedevent',
            name='repeat_interval_years',
            field=models.IntegerField(default=0, verbose_name='period in years, 0 if N/A'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='original amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget_only',
            field=models.BooleanField(default=False, verbose_name='Budget only, counts as 0 after today'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ismanual',
            field=models.BooleanField(default=False, verbose_name='Manual Intervention?'),
        ),
    ]
