# Generated by Django 4.0.2 on 2023-12-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0040_alter_cat2_options_alter_statement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat1',
            name='date_closed',
            field=models.DateField(blank=True, null=True, verbose_name='date closed'),
        ),
        migrations.AddField(
            model_name='cat1',
            name='date_open',
            field=models.DateField(blank=True, null=True, verbose_name='date opened'),
        ),
        migrations.AddField(
            model_name='cattype',
            name='date_closed',
            field=models.DateField(blank=True, null=True, verbose_name='date closed'),
        ),
        migrations.AddField(
            model_name='cattype',
            name='date_open',
            field=models.DateField(blank=True, null=True, verbose_name='date opened'),
        ),
    ]
