# Generated by Django 4.0.2 on 2023-12-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0041_cat1_date_closed_cat1_date_open_cattype_date_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat2',
            name='fuel',
            field=models.BooleanField(default=False, verbose_name='Do we keep quantity and cost per for this subcategory'),
        ),
    ]
