# Generated by Django 4.0.2 on 2023-12-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0042_cat2_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='prefered_accounts',
            field=models.ManyToManyField(related_name='accounts', to='budgetdb.Account'),
        ),
        migrations.AlterField(
            model_name='cat2',
            name='fuel',
            field=models.BooleanField(default=False, verbose_name='Is this fuel?  Do we keep quantity and cost per for this subcategory'),
        ),
    ]
