# Generated by Django 4.0.2 on 2023-12-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0043_preference_prefered_accounts_alter_cat2_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='prefered_accounts',
            new_name='favorite_accounts',
        ),
    ]
