# Generated by Django 4.0.2 on 2024-01-04 21:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0044_rename_prefered_accounts_preference_favorite_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='favorite_accounts',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='budgetdb.Account'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('amount_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='planned amount')),
                ('amount_planned_foreign_currency', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='original amount')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment')),
                ('ismanual', models.BooleanField(default=False, verbose_name='Manual Intervention?')),
                ('budget_only', models.BooleanField(default=False, verbose_name='Budget only, counts as 0 after today')),
                ('joined_order', models.IntegerField(blank=True, null=True, verbose_name='position in a joined transaction')),
                ('account_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account_destination', to='budgetdb.account')),
                ('account_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account_source', to='budgetdb.account')),
                ('cat1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='budgetdb.cat1', verbose_name='Category')),
                ('cat2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subcategory', to='budgetdb.cat2', verbose_name='Sub-Category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budgetdb.currency')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetdb.vendor')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
