# Generated by Django 4.0.2 on 2024-01-04 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0045_alter_preference_favorite_accounts_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object_owner_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='users_admin',
            field=models.ManyToManyField(blank=True, related_name='users_full_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='users_view',
            field=models.ManyToManyField(blank=True, related_name='users_view_access_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
