# Generated by Django 4.0.2 on 2024-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0046_template_owner_template_users_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetedevent',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='original amount'),
        ),
        migrations.AlterField(
            model_name='template',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='original amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_planned_foreign_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='original amount'),
        ),
    ]
