# Generated by Django 4.0.2 on 2024-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0047_alter_budgetedevent_amount_planned_foreign_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat2',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='special subcategory only used to transfer money between accounts.'),
        ),
    ]
