# Generated by Django 4.0.2 on 2024-01-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0048_cat2_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat2',
            name='transfer',
        ),
    ]
