# Generated by Django 4.0.2 on 2024-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0049_remove_cat2_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Unit_QTY',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Number of units'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Price per unit'),
        ),
    ]
