# Generated by Django 5.0.1 on 2024-01-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0052_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
