# Generated by Django 5.0.1 on 2024-01-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0054_user_email_key_user_email_verified_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
