# Generated by Django 5.0.1 on 2024-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0056_invitation_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='author',
        ),
        migrations.AddField(
            model_name='invitation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
