# Generated by Django 5.0.1 on 2024-01-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0057_remove_invitation_author_invitation_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='email_key',
        ),
    ]
