# Generated by Django 5.0.1 on 2024-01-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0058_remove_invitation_email_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited',
        ),
    ]
