# Generated by Django 5.0.1 on 2024-01-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0059_remove_user_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='users_admin',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='users_view',
        ),
    ]
